default:
  http_metas:
    content-type: text/html

  metas:
    title:        Dane Carder
    description:  Dane Carder
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, themes/base/ui.all.css]

  javascripts:    [jquery-1.2.3.pack.js, ui/ui.core.js, ui/ui.datepicker.js]

  has_layout:     on
  layout:         layout
