default:
  http_metas:
    content-type: text/html

  metas:
    title:        Dane Carder, Fine Art Painting :: Nashville, TN
    #description:  Dane Card Fine Artist
    #keywords:     Dane Carder, fine painting, Historical Art, Fine Arts, Nashville, TN, Tennessee, Painter, Artist
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, themes/base/ui.all.css]

  javascripts:    [jquery-1.2.3.pack.js, ui/ui.core.js, ui/ui.datepicker.js]

  has_layout:     on
  layout:         layout_home
