<?php

/**
 * dcPainting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    danecarder
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class dcPainting extends BasedcPainting
{
  public function postSave($event)
  {
    $obj = $event->getInvoker();
    
    $image_filename = sfConfig::get('sf_upload_dir').'/'.$obj->image;
    $thumb_filename = sfConfig::get('sf_upload_dir').'/thumbnails/'.$obj->thumbnail;
    
    if (is_file($image_filename))
    {
      $img = new sfImage($image_filename);
      $x = $img->getWidth();
      $y = $img->getHeight();
      if ($y > 475 || $x > 575)
      {
        if (img_is_tall($img))
        {
          $img->resize(0, 475, true, true);
        }
        else
        {
          $img->resize(575, 0, true, true);
        }
        
        $img->save();
      }
    }
    
    if (is_file($thumb_filename))
    {
      $img = new sfImage($thumb_filename);
      $x = $img->getWidth();
      $y = $img->getHeight();

      // check the dimensions (should be 40x40)
      if ($y > 40 && $x > 40)
      {
        if (img_is_tall($img))
        {
          $img->resize(40,0, true, true);
        }
        else
        {
          $img->resize(0,40, true, true);
        }

        $img->crop(null, null, 40, 40);
        $img->save();
      }
    }
  }
}

function img_is_tall(sfImage $img)
{
  $x = $img->getWidth();
  $y = $img->getHeight();

  if ($x > $y)
  {
    return false;
  }

  return true;
}