<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/10/03 20:50:38

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:dbname=dane_dane;host=localhost',
  'username' => 'root',
  'password' => 'root',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
