<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/10/03 20:49:59

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=dane_dane;host=localhost',
  'username' => 'dane_dane',
  'password' => '10stud10',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
