<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/10/03 20:51:35
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
