<?php
// auto-generated by sfViewConfigHandler
// date: 2010/10/03 20:49:59
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout_home' ? false : 'layout_home'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Dane Carder, Fine Art Painting :: Nashville, TN', false, false);
  $response->addMeta('description', 'Dane Carder', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('themes/base/ui.all.css', '', array ());
  $response->addJavascript('jquery-1.2.3.pack.js', '', array ());
  $response->addJavascript('ui/ui.core.js', '', array ());
  $response->addJavascript('ui/ui.datepicker.js', '', array ());


