propel:
  painting:
    id: ~
    title: { type: varchar(255), required: true, index: unique }
    medium: { type: varchar(255) }
    dimensions: { type: varchar(255) }
    date: { type: timestamp }
    description: { type: varchar(255) }
    category: { type: varchar(255) }
    subcategory: { type: varchar(255) }
    thumbnail: { type: varchar(255) }
    image: { type: varchar(255) }
    created_at: ~
    updated_at: ~
    
