default:
  http_metas:
    content-type: text/html

  metas:
    title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, themes/base/ui.all.css, jquery.jcarousel-rg.css, skin-rg.css]

  javascripts:    [jquery, ui/ui.core.js, ui/ui.datepicker.js, jquery.jcarousel.js]

  has_layout:     on
  layout:         layout
